# Meadow.Foundation pipeline
# Reference: https://aka.ms/yaml

trigger:
  - release
  - staging

variables:
  solution: "**/Meadow.Foundation.Drivers.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  internalFeedName: "Meadow02"

pool:
  vmImage: windows-2019

stages:
  - stage: Build
    jobs:
      - job: Build_Solution
        steps:
          - task: NuGetToolInstaller@1
            inputs:
              versionSpec: 5.8
          - task: NuGetCommand@2
            displayName: Use_Nugets
            inputs:
              feedsToUse: "select"
              vstsFeed: $(internalFeedName) #use internal feed
              restoreSolution: "$(solution)"
          - task: VSBuild@1
            inputs:
              solution: "$(solution)"
              platform: "$(buildPlatform)"
              configuration: "$(buildConfiguration)"
          - task: CopyFiles@2
            inputs:
              Contents: '**\*.nupkg'
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
              flattenFolders: true
              cleanTargetFolder: true
              overWrite: true
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: packages
